[package]
name = "asphyx"
version = "0.1.0"
edition = "2021"

[dependencies]
oxidx = { git = "https://github.com/if0ne/oxidx", version = "0.6.0" }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
winit = "0.30.9"
